apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-wordpress
  namespace: wordpress-pre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-wordpress
  template:
    metadata:
      labels:
        app: admin-wordpress
    spec:
      imagePullSecrets:
      - name: my-docker-credentials
      containers:
        - name: admin-wordpress
          image: udeccolima/phpmyadmin:wordpress-pre
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-wordpress-pre
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secret
                  key: phpmyadmin-password
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: admin-wordpress
  namespace: wordpress-pre
spec:
  type: ClusterIP
  selector:
    app: admin-wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80