apiVersion: v1
kind: Secret
metadata:
  name: root-secret
  namespace: wordpress-pre
type: kubernetes.io/base64
data:
  root-password: cjAyNz9sZSUtVzByZFByM3MhcCM1ZDIhPy1VZDN9ZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: proyecto-secret
  namespace: wordpress-pre
type: kubernetes.io/base64
data:
  proyecto-password: dXNlci1XMHJkUHIzc3AjNWQ/dy1VZDN9ZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secret
  namespace: wordpress-pre
type: kubernetes.io/base64
data:
  phpmyadmin-password: dXNlci1XMHJkUHIzc3AjNWQ/dy1VZDN9ZQ==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-wordpress-pre #Name for mysql service must be the same here and in the SVC
  namespace: wordpress-pre #NAMESPACE
spec:
  serviceName: "mysql-wordpress" #Name for mysql service
  replicas: 1
  selector:
    matchLabels:
      app: mysql-wordpress #Name for mysql service
  template:
    metadata:
      labels:
        app: mysql-wordpress  #Name for mysql service
    spec:
      containers:
        - name: mysql-wordpress-pre  #Name for mysql service
          image: mysql:8.1  #Docker Image
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-secret
                  key: root-password
            - name: TZ
              value: "America/Chihuahua"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: wordpress-mysql-pvc # REFERENCE: PVC NAME in storage yaml
              mountPath: /var/lib/mysql
            - name: wordpress-mysql-scripts  #Reference NAME = 1
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: wordpress-mysql-pvc # REFERENCE: PVC NAME in storage yaml
          persistentVolumeClaim:
            claimName: wordpress-mysql-pvc # REFERENCE: PVC NAME in storage yaml
        - name: wordpress-mysql-scripts  #Reference NAME = 1
          configMap:
            name: import-wordpress-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-wordpress-pre
  namespace: wordpress-pre
spec:
  selector:
    app: mysql-wordpress
  type: ClusterIP
  ports:
    - name: mysql-wordpress
      port: 3306
      targetPort: 3306