name: CI/CD on merge to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

env:
  DOCKER_IMAGE_NAME1: sistemasudec/wordpress:v1
  DOCKER_IMAGE_NAME2: sistemasudec/phpmyadmin:wordpress
  REMOTE_USER: digesetuser
  REMOTE_HOST: 148.213.1.131
  DEPLOY_PATH: /home/digesetuser/wordpress

jobs:
  build-container:
    name: Build container
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image 1
        run: |
          docker build -t $DOCKER_IMAGE_NAME1 ./public-html
          docker push $DOCKER_IMAGE_NAME1

      - name: Build and Push Docker Image 2
        run: |
          docker build -t $DOCKER_IMAGE_NAME2 ./phpmyadmin
          docker push $DOCKER_IMAGE_NAME2

      - name: Logout from Docker Hub
        run: docker logout

      - name: Set up SSH Keys
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Kubernetes Config Files
        run: |
          scp -o StrictHostKeyChecking=no deployments/*.yaml ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.DEPLOY_PATH }}

      - name: Apply Kubernetes storage
        uses: myrotvorets/kubectl-action@2.0.0
        with:
            config: ${{ secrets.KUBE_CONFIG_DATA }}
            version: latest
            args: apply -f deployments/storage.yaml --timeout=120s

      - name: Apply Kubernetes satefulset
        uses: myrotvorets/kubectl-action@2.0.0
        with:
            config: ${{ secrets.KUBE_CONFIG_DATA }}
            version: latest
            args: apply -f deployments/statefulset.yaml --timeout=120s

      - name: Apply Kubernetes deployments
        uses: myrotvorets/kubectl-action@2.0.0
        with:
            config: ${{ secrets.KUBE_CONFIG_DATA }}
            version: latest
            args: apply -f deployments/ --timeout=120s
      
      - name: Apply Kubernetes configmap
        uses: myrotvorets/kubectl-action@2.0.0
        with:
            config: ${{ secrets.KUBE_CONFIG_DATA }}
            version: latest
            args: apply -f deployments/configmap.yaml --timeout=120s

      - name: Restart Deployment
        uses: myrotvorets/kubectl-action@2.0.0
        with:
            config: ${{ secrets.KUBE_CONFIG_DATA }}
            version: latest
            args: rollout restart deployment wordpress -n wordpress

      - name: Notify Success on Slack
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
            channel-id: 'C06HDV6HZLG' # channel name
            slack-message: "✅ *${{ github.workflow }}* workflow SUCCEEDED for ${{ github.repository }}. <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>\nGitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Failure on Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
            channel-id: 'C06HDV6HZLG' # channel name
            slack-message: "❌ *${{ github.workflow }}* workflow FAILED for ${{ github.repository }}. <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>\nGitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}