apiVersion: v1
kind: ConfigMap
metadata:
  name: import-wordpress-scripts
  namespace: wordpress
data:
  wordpress.sql: |
    CREATE DATABASE IF NOT EXISTS wordpress;
    USE wordpress;
    CREATE USER 'user'@'%' IDENTIFIED BY 'user-W0rdPr3sp#5d?w-Ud3}e';
    GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
    CREATE USER 'read'@'%' IDENTIFIED BY '$read-secure-psswrd&';
    GRANT SELECT ON wordpress.* TO 'read'@'%';
    CREATE USER 'write'@'%' IDENTIFIED BY '=access-for-write-user##';
    GRANT SELECT, INSERT, UPDATE, DELETE ON wordpress.* TO 'write'@'%';
    FLUSH PRIVILEGES;